Problem Statement :

The Most Dangerous city in Jammu and Kashmir and the terrorist group which is most active in that city?

Print count of number of attacks in that city as integer value.

Note:Ignoring the Unknown Terrorist Group.Here Dangerous related with the number of terrorist attacks.



ans >>> Srinagar 657 Muslim Separatists

In [14]:
import pandas as pd

In [7]:
df = pd.read_csv(r"data set\\terrorismData.csv")
df = df[df.State == 'Jammu and Kashmir']
city_count = df.City.value_counts()
c = city_count.index[0]
no = city_count[0]
df= df[df.City == c]
grp = df.Group.value_counts()
g = grp.index[1]
print(c,no, g)

Unknown                               306
Muslim Separatists                     55
Jammu and Kashmir Liberation Front     45
Kashmiri extremists                    37
Muslim Militants                       35
Name: Group, dtype: int64
Srinagar 657 Muslim Separatists

In [9]:
df.head()

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
0,1970,7,2,Dominican Republic,NaN,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,Assassination,1.0,0.0,Julio Guzman,NaN,MANO-D,Private Citizens & Property,Unknown
1,1970,0,0,Mexico,Federal,North America,Mexico city,19.371887,-99.086624,Hostage Taking (Kidnapping),0.0,0.0,"Nadine Chaval, daughter",NaN,23rd of September Communist League,Government (Diplomatic),Unknown
2,1970,1,0,Philippines,Tarlac,Southeast Asia,Unknown,15.478598,120.599741,Assassination,1.0,0.0,Employee,NaN,Unknown,Journalists & Media,Unknown
3,1970,1,0,Greece,Attica,Western Europe,Athens,37.997490,23.762728,Bombing/Explosion,NaN,NaN,U.S. Embassy,NaN,Unknown,Government (Diplomatic),Explosives
4,1970,1,0,Japan,Fukouka,East Asia,Fukouka,33.580412,130.396361,Facility/Infrastructure Attack,NaN,NaN,U.S. Consulate,NaN,Unknown,Government (Diplomatic),Incendiary

In [18]:
print(df.State.unique())
df.isnull().sum()

array([nan, 'Federal', 'Tarlac', ..., 'Carlow', 'Western Lakes',
       'Vidzeme'], dtype=object)

In [24]:
df = df[df.State == 'Jammu and Kashmir']
df.head()

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
21744,1984,4,17,India,Jammu and Kashmir,South Asia,Bhela,33.315527,74.622476,Assassination,2.0,0.0,Gurbachan Singh Sandhar (Sikh lawyer) and wife,NaN,Sikh Extremists,Private Citizens & Property,Unknown
22108,1984,5,20,India,Jammu and Kashmir,South Asia,Jammu,32.726602,74.857026,Bombing/Explosion,1.0,0.0,bridge over a stream,NaN,Unknown,Transportation,Explosives
29677,1986,12,11,India,Jammu and Kashmir,South Asia,Madora,33.934929,75.154160,Bombing/Explosion,1.0,5.0,general post office complex,NaN,Unknown,Government (General),Unknown
33202,1988,1,21,India,Jammu and Kashmir,South Asia,Mand,32.888165,74.985168,Armed Assault,2.0,0.0,police unit,NaN,Unknown,Police,Firearms
33372,1988,2,7,India,Jammu and Kashmir,South Asia,Kherawali,32.523889,74.974444,Armed Assault,4.0,5.0,marriage reception,NaN,Sikh Extremists,Private Citizens & Property,Firearms

In [30]:
city_count = df.City.value_counts()
print(city_count)

Srinagar     657
Sopore       102
Unknown       86
Anantnag      76
Jammu         57
            ...
Bragam         1
Narsu          1
Lasjan         1
Goriwan        1
Lethapora      1
Name: City, Length: 633, dtype: int64

In [41]:
city = city_count.index[0]
no = city_count[0]
print(city, no)

Srinagar 657

In [45]:
df = df[df.City == city]
grp = df.Group.value_counts()
g = grp.index[1]
grp

Unknown                               306
Muslim Separatists                     55
Jammu and Kashmir Liberation Front     45
Kashmiri extremists                    37
Muslim Militants                       35
Hizbul Mujahideen (HM)                 31
Separatists                            21
Lashkar-e-Taiba (LeT)                  21
Jaish-e-Mohammad (JeM)                 12
Al-Mansoorian                          12
Sikh Extremists                         9
Al-Umar Mujahideen                      8
Jamiat ul-Mujahedin (JuM)               6
Lashkar-e-Islam (India)                 4
Al-Madina                               4
Islamic Front                           3
Muslim extremists                       3
Tehrik al-Mojahedin                     3
Al-Arifeen                              3
Kashmiri Hezbollah                      3
Jammu and Kashmir Islamic Front         2
Ikhwan-ul-Muslimeen                     2
Muslim Brotherhood                      2
Muslim Janbaz Force                     2
Mujahideen Kashmir                      2
Allah's Tigers                          2
Islamic Movement of Kashmir             2
Al-Fajr                                 1
Al-Badr                                 1
Al-Nasireen Group                       1
Al-Shuda Brigade                        1
Save Kashmir Movement                   1
Kashmir Freedom Force                   1
Muslim Rebels                           1
Al-Nasirin (India)                      1
Harakat ul-Mujahidin (HuM)              1
Gunmen                                  1
Lashkar-e-Jhangvi                       1
Al-Hamas Mujahideen                     1
Militants                               1
Pro-Pakistani extremists                1
Ikhwan Jammu and Kashmir                1
Dukhta-ran-e-Millat                     1
Muslims                                 1
Al-Jehad                                1
Lashkari-e-Adam (Army of Adam)          1
Al-Fatah                                1
Achwan-I-Mushbani                       1
Quit Kashmir Movement (QKM)             1
Name: Group, dtype: int64

In [46]:
g

'Muslim Separatists'

In [8]:
df.head()

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
35266,1988,7,31,India,Jammu and Kashmir,South Asia,Srinagar,34.08374,74.789902,Bombing/Explosion,0.0,0.0,Srinagar Club,NaN,Sikh Extremists,Private Citizens & Property,Explosives
35267,1988,7,31,India,Jammu and Kashmir,South Asia,Srinagar,34.08374,74.789902,Bombing/Explosion,0.0,0.0,Telegraph Office,NaN,Sikh Extremists,Business,Explosives
36073,1988,10,27,India,Jammu and Kashmir,South Asia,Srinagar,34.08374,74.789902,Bombing/Explosion,0.0,9.0,Street,NaN,Unknown,Private Citizens & Property,Explosives
36074,1988,10,27,India,Jammu and Kashmir,South Asia,Srinagar,34.08374,74.789902,Bombing/Explosion,0.0,8.0,Police Unit,NaN,Muslim Militants,Police,Explosives
36078,1988,10,27,India,Jammu and Kashmir,South Asia,Srinagar,34.08374,74.789902,Armed Assault,1.0,0.0,Police Unit,NaN,Muslim Militants,Police,Firearms

In [32]:
df = pd.read_csv(r"data set\\terrorismData.csv")

There was formation of new government in India on 26 May 2014. So current government's span is from 26th May 2014 to current. Find out two things from this period-

In [36]:
df = df[(df.Country == 'India') & (df.Year >= 2014) & (df.Month >= 5)]
df

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
132768,2014,6,1,India,Manipur,South Asia,Senapati district,25.273753,94.027276,Hostage Taking (Kidnapping),0.0,0.0,Trucker: Pradeep Dungana,06/01/2014: Assailants kidnapped a truck drive...,Kuki Revolutionary Army (KRA),Private Citizens & Property,Firearms
132796,2014,6,1,India,Chhattisgarh,South Asia,Bijapur district,18.846484,80.745099,Armed Assault,1.0,0.0,Civilian: Devendra Modem,06/01/2014: Assailants attacked a civilian in ...,Maoists,Private Citizens & Property,Melee
132830,2014,6,2,India,Assam,South Asia,Jekabari,25.563479,89.890889,Hostage Taking (Kidnapping),0.0,0.0,Shoe Trader: Fozal Haque,06/02/2014: Assailants kidnapped a trader from...,Garo National Liberation Army,Private Citizens & Property,Firearms
132873,2014,6,3,India,Chhattisgarh,South Asia,Bijapur,18.797710,80.812864,Bombing/Explosion,0.0,0.0,Unknown,06/03/2014: An explosive device was discovered...,Unknown,Unknown,Explosives
132879,2014,6,3,India,Jharkhand,South Asia,Khunti district,23.070000,85.280000,Armed Assault,3.0,0.0,"Civilians: Dubraj Manki, Nagi Manki, Surya Hansda",06/03/2014: Assailants shot and killed three v...,Maoists,Private Citizens & Property,Firearms
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181663,2017,12,30,India,Kerala,South Asia,Koothuparamba,11.831902,75.565432,Bombing/Explosion,0.0,0.0,Koothuparamba Police Station,12/30/2017: Assailants threw an explosive devi...,Unknown,Police,Explosives
181665,2017,12,30,India,Chhattisgarh,South Asia,Toylanka,18.802725,81.497666,Facility/Infrastructure Attack,0.0,0.0,Road Construction Site,12/30/2017: Assailants set fire to seven vehic...,Communist Party of India - Maoist (CPI-Maoist),Business,Firearms
181672,2017,12,31,India,Jammu and Kashmir,South Asia,Lethapora,33.966527,74.964225,Armed Assault,8.0,3.0,Camp,12/31/2017: Assailants armed with grenades and...,Jaish-e-Mohammad (JeM),Police,Explosives
181684,2017,12,31,India,Assam,South Asia,Hungrum,25.180162,93.015788,Hostage Taking (Kidnapping),0.0,0.0,Personal Security Officer of Council Member Ih...,12/31/2017: Assailants abducted Prafulla Phuka...,Zeliangrong United Front,Government (General),Firearms
181689,2017,12,31,India,Manipur,South Asia,Imphal,24.798346,93.940430,Bombing/Explosion,0.0,0.0,Office,12/31/2017: Assailants threw a grenade at a Fo...,Unknown,Government (General),Explosives

In [37]:
len(df)

2101

Most Deadliest attack in a history of HumanKind?

Print count of Killed people as integer value.

Note: Here Deadliest attack means, in which the most number of people killed.

In [38]:
df = pd.read_csv(r"data set\\terrorismData.csv")
df.head()

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
0,1970,7,2,Dominican Republic,NaN,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,Assassination,1.0,0.0,Julio Guzman,NaN,MANO-D,Private Citizens & Property,Unknown
1,1970,0,0,Mexico,Federal,North America,Mexico city,19.371887,-99.086624,Hostage Taking (Kidnapping),0.0,0.0,"Nadine Chaval, daughter",NaN,23rd of September Communist League,Government (Diplomatic),Unknown
2,1970,1,0,Philippines,Tarlac,Southeast Asia,Unknown,15.478598,120.599741,Assassination,1.0,0.0,Employee,NaN,Unknown,Journalists & Media,Unknown
3,1970,1,0,Greece,Attica,Western Europe,Athens,37.997490,23.762728,Bombing/Explosion,NaN,NaN,U.S. Embassy,NaN,Unknown,Government (Diplomatic),Explosives
4,1970,1,0,Japan,Fukouka,East Asia,Fukouka,33.580412,130.396361,Facility/Infrastructure Attack,NaN,NaN,U.S. Consulate,NaN,Unknown,Government (Diplomatic),Incendiary

In [39]:
df.dropna()

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
5,1970,1,1,United States,Illinois,North America,Cairo,37.005105,-89.176269,Armed Assault,0.0,0.0,Cairo Police Headquarters,1/1/1970: Unknown African American assailants ...,Black Nationalists,Police,Firearms
7,1970,1,2,United States,California,North America,Oakland,37.791927,-122.225906,Bombing/Explosion,0.0,0.0,Edes Substation,1/2/1970: Unknown perpetrators detonated explo...,Unknown,Utilities,Explosives
8,1970,1,2,United States,Wisconsin,North America,Madison,43.076592,-89.412488,Facility/Infrastructure Attack,0.0,0.0,"R.O.T.C. offices at University of Wisconsin, M...","1/2/1970: Karl Armstrong, a member of the New ...",New Year's Gang,Military,Incendiary
9,1970,1,3,United States,Wisconsin,North America,Madison,43.072950,-89.386694,Facility/Infrastructure Attack,0.0,0.0,Selective Service Headquarters in Madison Wisc...,"1/3/1970: Karl Armstrong, a member of the New ...",New Year's Gang,Government (General),Incendiary
11,1970,1,6,United States,Colorado,North America,Denver,39.758968,-104.876305,Facility/Infrastructure Attack,0.0,0.0,"Army Recruiting Station, Denver Colorado",1/6/1970: Unknown perpetrators threw a Molotov...,Left-Wing Militants,Military,Incendiary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181686,2017,12,31,Somalia,Middle Shebelle,Sub-Saharan Africa,Ceelka Geelow,2.359673,45.385034,Armed Assault,1.0,2.0,Checkpoint,12/31/2017: Assailants opened fire on a Somali...,Al-Shabaab,Military,Firearms
181687,2017,12,31,Syria,Lattakia,Middle East & North Africa,Jableh,35.407278,35.942679,Bombing/Explosion,2.0,7.0,Hmeymim Air Base,12/31/2017: Assailants launched mortars at the...,Muslim extremists,Military,Explosives
181688,2017,12,31,Philippines,Maguindanao,Southeast Asia,Kubentog,6.900742,124.437908,Facility/Infrastructure Attack,0.0,0.0,Houses,12/31/2017: Assailants set fire to houses in K...,Bangsamoro Islamic Freedom Movement (BIFM),Private Citizens & Property,Incendiary
181689,2017,12,31,India,Manipur,South Asia,Imphal,24.798346,93.940430,Bombing/Explosion,0.0,0.0,Office,12/31/2017: Assailants threw a grenade at a Fo...,Unknown,Government (General),Explosives
181690,2017,12,31,Philippines,Maguindanao,Southeast Asia,Cotabato City,7.209594,124.241966,Bombing/Explosion,0.0,0.0,Unknown,12/31/2017: An explosive device was discovered...,Unknown,Unknown,Explosives

In [45]:
a =df.Killed.max()
a

1570.0

In [49]:
df.describe()

,Year,Month,Day,Latitude,Longitude,Killed,Wounded
count,181691.000000,181691.000000,181691.000000,177135.000000,1.771340e+05,171378.000000,165380.000000
mean,2002.638997,6.467277,15.505644,23.498343,-4.586957e+02,2.403272,3.167668
std,13.259430,3.388303,8.814045,18.569242,2.047790e+05,11.545741,35.949392
min,1970.000000,0.000000,0.000000,-53.154613,-8.618590e+07,0.000000,0.000000
25%,1991.000000,4.000000,8.000000,11.510046,4.545640e+00,0.000000,0.000000
50%,2009.000000,6.000000,15.000000,31.467463,4.324651e+01,0.000000,0.000000
75%,2014.000000,9.000000,23.000000,34.685087,6.871033e+01,2.000000,2.000000
max,2017.000000,12.000000,31.000000,74.633553,1.793667e+02,1570.000000,8191.000000

In [52]:
df= df[df.Killed == 1570]

In [53]:
df

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
133518,2014,6,12,Iraq,Saladin,Middle East & North Africa,Tikrit,34.621521,43.668377,Hostage Taking (Kidnapping),1570.0,NaN,Soldiers,06/12/2014: Assailants abducted approximately ...,Islamic State of Iraq and the Levant (ISIL),Military,Firearms

In [56]:
print(int(a), *df.Country, *df.Group)

1570 Iraq Islamic State of Iraq and the Levant (ISIL)